### ISSUE TITLE
Prvni ukol - bez bonusu

### ISSUE THREAD

**Issue by prachyn** [prachyn/Python#1]
Ahoj,
zatim takto prvni ukol bez bonusu. To kdybych se k nim nedostal. ;-)

ukol.py

Tomas

**Comment by sytraaak** [comment]
Zadání je určitě splněno, takže vše ok, spíše drobnosti v čitelnosti kódu, případně viz komentáře v [tomto](https://github.com/prachyn/Python/pull/2/commits/be2e0e5d93c793b99de96fc14ab037bcd285e4f5) requestu.
