### ISSUE TITLE
2. uloha

### ISSUE THREAD

**Issue by prachyn** [prachyn/Python#3]
Ahoj,
tentokrat i s bonusem. To se mi mozna bude hodit v praci. Jeste tak API pro registr dluzniku. Nemas? ;-)

ukol2.py

Tomas

**Comment by sytraaak** [comment]
@prachyn kouknu na to ASAP, ale na první dobrou to vypadá v pohodě :-)

**Comment by sytraaak** [comment]
@prachyn kód je určitě funkčí, dovolil jsem si však pár komentářů v commitu [zde](https://github.com/prachyn/Python/pull/4/commits/0230b1f35bd59e22f915f00e7adbf6d5811412a9)

Obecně:
- funkce pojmenovávat anglicky
- funkce by měly něco vracet a také příjimat nějaké parametry (ne vždy, ale zde to dává smysl)
- funkce mohou být univerzálnější, pokud jsou inputy od uživatele mimo danou funkci
- volání funkcí až na konci kódu, pořadí python kódu je: importy (build in knihovny, importované knihovny, vlastní knihovny), definice tříd (zde žádné nejsou), definice funkcí a poté samotný kód
- ošetření status kódů je fajn praxe, pokud však vrátí chybu, je dobré vědět, jaký status code se vrátil, doplněno do chybových hlášek

Jinak určitě považuji úkol za splněný, spíše tohle vše jen dodávám jako zpětnou vazbu :-)

Edit: Jo a taky ten repozitář by byl fajn na každý "projekt" zvlášt :D 

Díky za zpracování
